import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/layouts/Navbar';
import Logo from './components/shared/Logo';
import FilterContextProvider from './contexts/useFilter';
import Footer from './components/layouts/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Japan Auto Base',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FilterContextProvider>
        <body className={inter.className}>
          <Navbar />
          <Logo />
          <main>{children}</main>
          <Footer />
        </body>
      </FilterContextProvider>
    </html>
  );
}
